name: vault_calculator
description: A calculator app with hidden vault functionality.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.6
  file_picker: ^8.0.0
  path_provider: ^2.1.2
  encrypt: ^5.0.3
  pointycastle: ^3.7.3
  crypto: ^3.0.3
  mime: ^1.0.5
  open_filex: ^4.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/app_icon.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.jpg"
  min_sdk_android: 21